const navLinks = [
    { name: "Home", path: "/" },
    { name: "Timeline", path: "/timeline" },
    { name: "Gallery", path: "/gallery" },
];

const models = [
    { name: "iPhone", releaseYear: "2007", tagline: "Apple reinvents the phone.", image: "/images/full/iPhone-2G.png" },
    { name: "iPhone 3G", releaseYear: "2008", tagline: "The first phone to beat the iPhone", image: "/images/full/iPhone-3G.jpg" },
    { name: "iPhone 3GS", releaseYear: "2009", tagline: "The fastest, smartest phone yet", image: "/images/full/iPhone-3GS.jpg" },
    { name: "iPhone 4", releaseYear: "2010", tagline: "This changes everything. Again.", image: "/images/full/iPhone-4.jpg" },
    { name: "iPhone 4s", releaseYear: "2011", tagline: "The most amazing iPhone yet", image: "/images/full/iPhone-4s.jpg" },
    { name: "iPhone 5", releaseYear: "2012", tagline: "The biggest thing to happen to iPhone since iPhone", image: "/images/full/iPhone-5.jpg" },
    { name: "iPhone 5s", releaseYear: "2013", tagline: "Forward thinking", image: "/images/full/iPhone-5s.jpg" },
    { name: "iPhone 5c", releaseYear: "2013", tagline: "For the colourful", image: "/images/full/iPhone-5c.jpg" },
    { name: "iPhone 6", releaseYear: "2014", tagline: "Bigger than bigger", image: "/images/full/iPhone-6.jpg" },
    { name: "iPhone 6s", releaseYear: "2015", tagline: "The only thing that's changed is everything.", image: "/images/full/iPhone-6s.jpg" },
    { name: "iPhone SE", releaseYear: "2016", tagline: "A big step for small.", image: "/images/full/iPhone-SE.jpg" },
    { name: "iPhone 7", releaseYear: "2016", tagline: "This is 7.", image: "/images/full/iPhone-7.jpg" },
    { name: "iPhone 8", releaseYear: "2017", tagline: "A new generation of iPhone.", image: "/images/full/iPhone-8.png" },
    { name: "iPhone X", releaseYear: "2017", tagline: "Say hello to the future.", image: "/images/full/iPhone-X.jpg" },
    { name: "iPhone XS", releaseYear: "2018", tagline: "Welcome to the big screens", image: "/images/full/iPhone-XS.jpg" },
    { name: "iPhone XR", releaseYear: "2018", tagline: "Brilliant. In every way.", image: "/images/full/iPhone-XR.jpg" },
    { name: "iPhone 11", releaseYear: "2019", tagline: "Just the right amount of everything.", image: "/images/full/iPhone-11.jpg" },
    { name: "iPhone 11 Pro", releaseYear: "2019", tagline: "And then there was Pro.", image: "/images/full/iPhone-11Pro.jpg" },
    { name: "iPhone SE", releaseYear: "2020", tagline: "Lots to live. Less to spend.", image: "/images/full/iPhone-SE2.jpg" },
    { name: "iPhone 12", releaseYear: "2020", tagline: "Blast past fast.", image: "/images/full/iPhone-12.png" },
    { name: "iPhone 12 Pro", releaseYear: "2020", tagline: "It's a leap year.", image: "/images/full/iPhone-12Pro.jpg" },
    { name: "iPhone 13", releaseYear: "2021", tagline: "Your new superpower.", image: "/images/full/iPhone-13.png" },
    { name: "iPhone 13 Pro", releaseYear: "2021", tagline: "Oh. So. Pro.", image: "/images/full/iPhone-13Pro.png" },
    { name: "iPhone SE", releaseYear: "2022", tagline: "Love the power. Love the price.", image: "/images/full/iPhone-SE3.png" },
    { name: "iPhone 14", releaseYear: "2022", tagline: "Big and bigger.", image: "/images/full/iPhone-14.png" },
    { name: "iPhone 14 Pro", releaseYear: "2022", tagline: "Pro. Beyond.", image: "/images/full/iPhone-14Pro.png" },
    { name: "iPhone 15", releaseYear: "2023", tagline: "New camera. New design. Newphoria.", image: "/images/full/iPhone-15.png" },
    { name: "iPhone 15 Pro", releaseYear: "2023", tagline: "Titanium. So strong. So light. So Pro.", image: "/images/full/iPhone-15Pro.png" },
    { name: "iPhone 16", releaseYear: "2024", tagline: "Hello, Apple Intelligence.", image: "/images/full/iPhone-16.png" },
    { name: "iPhone 16 Pro", releaseYear: "2024", tagline: "Hello, Apple Intelligence.", image: "/images/full/iPhone-16Pro.png" },
    { name: "iPhone 16e", releaseYear: "2025", tagline: "Everything you love. Including the price.", image: "/images/full/iPhone-16e.png" },
    { name: "iPhone 17", releaseYear: "2025", tagline: "Magichromatic.", image: "/images/full/iPhone-17.png" },
    { name: "iPhone Air", releaseYear: "2025", tagline: "The thinnest iPhone ever. With the power of Pro inside.", image: "/images/full/iPhone-Air.png" },
    { name: "iPhone 17 Pro", releaseYear: "2025", tagline: "The Ultimate Pro.", image: "/images/full/iPhone-17Pro.png" },
    { name: "iPhone 17e", releaseYear: "2026", tagline: "Feature stacked. Value packed.", image: "/images/full/iPhone-17e.jpg" },
    { name: "iPhone 18 Pro", releaseYear: "2026", tagline: "Pro further.", image: "/images/full/iPhone-2G.png" },
    { name: "iPhone Duo", releaseYear: "2026", tagline: "Hello, hello.", image: "/images/full/iPhone-Duo.png" },
];

const iOS = [
    { name: "iPhone OS 1", icon: "/images/icons/iOS/iOS-1.png" },
    { name: "iPhone OS 2", icon: "/images/icons/iOS/iOS-2.png" },
    { name: "iPhone OS 3", icon: "/images/icons/iOS/iOS-3.png" },
    { name: "iOS 4", icon: "/images/icons/iOS/iOS-4.png" },
    { name: "iOS 5", icon: "/images/icons/iOS/iOS-5.png" },
    { name: "iOS 6", icon: "/images/icons/iOS/iOS-6.png" },
    { name: "iOS 7", icon: "/images/icons/iOS/iOS-7.png" },
    { name: "iOS 8", icon: "/images/icons/iOS/iOS-8.png" },
    { name: "iOS 9", icon: "/images/icons/iOS/iOS-9.png" },
    { name: "iOS 10", icon: "/images/icons/iOS/iOS-10.png" },
    { name: "iOS 11", icon: "/images/icons/iOS/iOS-11.png" },
    { name: "iOS 12", icon: "/images/icons/iOS/iOS-12.png" },
    { name: "iOS 13", icon: "/images/icons/iOS/iOS-13.png" },
    { name: "iOS 14", icon: "/images/icons/iOS/iOS-14.png" },
    { name: "iOS 15", icon: "/images/icons/iOS/iOS-15.png" },
    { name: "iOS 16", icon: "/images/icons/iOS/iOS-16.png" },
    { name: "iOS 17", icon: "/images/icons/iOS/iOS-17.png" },
    { name: "iOS 18", icon: "/images/icons/iOS/iOS-18.png" },
    { name: "iOS 26", icon: "/images/icons/iOS/iOS-26.png" },
    { name: "iOS 27", icon: "/images/icons/iOS/iOS-27.png" },
];

const processors = [
    { name: "A4", icon: "/imgaes/processors/a4-chip.jpeg" },
    { name: "A5", icon: "/imgaes/processors/a5-chip.jpeg" },
    { name: "A6", icon: "/imgaes/processors/a6-chip.jpeg" },
    { name: "A7", icon: "/imgaes/processors/a7-chip.jpeg" },
    { name: "A8", icon: "/imgaes/processors/a8-chip.jpeg" },
    { name: "A9", icon: "/imgaes/processors/a9-chip.jpeg" },
    { name: "A10 Fusion", icon: "/imgaes/processors/a10-fusion-chip.jpeg" },
    { name: "A11 Bionic", icon: "/imgaes/processors/a11-bionic-chip.jpeg" },
    { name: "A12 Bionic", icon: "/imgaes/processors/a12-bionic-chip.jpeg" },
    { name: "A13 Bionic", icon: "/imgaes/processors/a13-bionic-chip.jpeg" },
    { name: "A14 Bionic", icon: "/imgaes/processors/a14-bionic-chip.jpeg" },
    { name: "A15 Bionic", icon: "/imgaes/processors/a15-bionic-chip.jpeg" },
    { name: "A16 Bionic", icon: "/imgaes/processors/a16-bionic-chip.jpeg" },
    { name: "A17 Pro", icon: "/imgaes/processors/a17-pro-chip.png" },
    { name: "A18 Pro", icon: "/imgaes/processors/a18-pro-chip.png" },
    { name: "A19 Pro", icon: "/imgaes/processors/a19-pro-chip.png" },
    { name: "A20 Pro", icon: "/imgaes/processors/a4-chip.jpeg" },
]

export {
    navLinks, models, iOS,
}